language: java
jdk:
 - oraclejdk8
before_install:
 - "export DISPLAY=:99.0"
 - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -extension RANDR -screen 0 1280x1024x16"
 - chmod +x gradlew